In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
colors=[0,0,0,0,0,1,1,1,0,0,0,0,2,0,2,0,0]  # say this came from a board with 4 rows

In [16]:
colors=loadtxt('test_colors.txt',delimiter=',')
print(colors)

[0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 2. 0. 2. 0. 0.]


* to do - reading from text file

In [17]:
length_of_color_list=len(colors)
length_per_square=length_of_color_list//4  # make it an integer
L=length_per_square

In [18]:
for i in range(4):
    print(L*i,L*(i+1))
    print(colors[L*i:L*(i+1)])

0 4
[0. 0. 0. 0.]
4 8
[0. 1. 1. 1.]
8 12
[0. 0. 0. 0.]
12 16
[2. 0. 2. 0.]


In [19]:
for i in range(4):
    print(L*i,L*(i+1))
    sublist=array(colors[L*i:L*(i+1)])
    print(sublist)
    if any(sublist==1):
        print("player 1")
    elif any(sublist==2):
        print("player 2")        

0 4
[0. 0. 0. 0.]
4 8
[0. 1. 1. 1.]
player 1
8 12
[0. 0. 0. 0.]
12 16
[2. 0. 2. 0.]
player 2


In [20]:
from Game import *

In [21]:
state=Board(4,2)

for i in range(4):
    print(L*i,L*(i+1))
    sublist=array(colors[L*i:L*(i+1)])
    print(sublist)
    if any(sublist==1):
        print("player 1")
        state[i,0]=1
    elif any(sublist==2):
        print("player 2")        
        state[i,0]=2
    else:
        state[i,0]=0


0 4
[0. 0. 0. 0.]
4 8
[0. 1. 1. 1.]
player 1
8 12
[0. 0. 0. 0.]
12 16
[2. 0. 2. 0.]
player 2


In [22]:
state

 0  0 
 1  0 
 0  0 
 2  0 

In [23]:
loadtxt?

Signature: loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes')
Docstring:
Load data from a text file.

Each row in the text file must have the same number of values.

Parameters
----------
fname : file, str, or pathlib.Path
    File, filename, or generator to read.  If the filename extension is
    ``.gz`` or ``.bz2``, the file is first decompressed. Note that
    generators should return byte strings for Python 3k.
dtype : data-type, optional
    Data-type of the resulting array; default: float.  If this is a
    structured data-type, the resulting array will be 1-dimensional, and
    each row will be interpreted as an element of the array.  In this
    case, the number of columns used must match the number of fields in
    the data-type.
comments : str or sequence of str, optional
    The characters or list of characters used to indicate the start of a
    comment. None implies no comm