In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
from science import *

In [17]:
from random import choice

http://mnemstudio.org/path-finding-q-learning.htm

<img src="images/map3a.gif">

<img src="images/r_matrix1.gif">

The -1's in the table represent null values (i.e.; where there isn't a link between nodes). For example, State 0 cannot go to State 1.

The Q-Learning algorithm goes as follows:

1. Set the gamma parameter, and environment rewards in matrix R.

2. Initialize matrix Q to zero.

3. For each episode:

Select a random initial state.

Do While the goal state hasn't been reached.

Select one among all possible actions for the current state.
Using this possible action, consider going to the next state.
Get maximum Q value for this next state based on all possible actions.
Compute: 

Q(state, action) = R(state, action) + Gamma * Max[Q(next state, all actions)]

Set the next state as the current state.
End Do

End For

In [8]:
Q=np.zeros((6,6))
Q

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

<img src="images/map3a.gif">

In [35]:
R=np.zeros((6,6))*np.nan
for row,col in [ (0,4), (1,3) , (2,3) , (3,4) ,(4,5) ,(1,5)]:
    R[row,col]=0
    R[col,row]=0

for row,col in [ (4,5), (1,5),(5,5) ]:
    R[row,col]=100
    
R

array([[ nan,  nan,  nan,  nan,   0.,  nan],
       [ nan,  nan,  nan,   0.,  nan, 100.],
       [ nan,  nan,  nan,   0.,  nan,  nan],
       [ nan,   0.,   0.,  nan,   0.,  nan],
       [  0.,  nan,  nan,   0.,  nan, 100.],
       [ nan,   0.,  nan,  nan,   0., 100.]])

In [48]:
γ=0.8
goal_state=5

<img src="images/r_matrix1.gif">

In [36]:
all_states=[0,1,2,3,4,5]
all_actions=[0,1,2,3,4,5]

current_state=choice(all_states)

all_actions=[0,1,2,3,4,5]
available_actions=[col for col in range(6) if not isnan(R[current_state,col])]

current_state,available_actions

(2, [3])

Let's follow the example they go through, to see if we get the same number

In [45]:
state=1

available_actions=[col for col in range(6) if not isnan(R[state,col])]
print(state,available_actions)

#by random selection we choose 5
action=5
print("action",action)

next_state=action
available_next_actions=[col for col in range(6) if not isnan(R[next_state,col])]

1 [3, 5]
action 5


Q(state, action) = R(state, action) + Gamma * Max[Q(next state, all actions)]

Q(1, 5) = R(1, 5) + 0.8 * Max[Q(5, 1), Q(5, 4), Q(5, 5)] = 100 + 0.8 * 0 = 100

In [46]:
Q[state,action]=R[state,action] + γ * max([Q[next_state,a] for a in available_next_actions])
Q

array([[  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., 100.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.]])

now we choose 3 as the state

In [47]:
state=3

available_actions=[col for col in range(6) if not isnan(R[state,col])]
print(state,available_actions)

#by random selection we choose 1
action=1
print("action",action)

next_state=action
available_next_actions=[col for col in range(6) if not isnan(R[next_state,col])]
Q[state,action]=R[state,action] + γ * max([Q[next_state,a] for a in available_next_actions])
print(Q)

state=next_state

available_actions=[col for col in range(6) if not isnan(R[state,col])]
print(state,available_actions)

#by random selection we choose 5
action=5
print("action",action)

next_state=action
available_next_actions=[col for col in range(6) if not isnan(R[next_state,col])]
Q[state,action]=R[state,action] + γ * max([Q[next_state,a] for a in available_next_actions])
print(Q)


3 [1, 2, 4]
action 1
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.  80.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
1 [3, 5]
action 5
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.  80.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]


## now loop

In [56]:
for i in range(100):
    while True:
        state=choice(all_states)

        available_actions=[col for col in range(6) if not isnan(R[state,col])]
#        print(state,available_actions)

        #by random selection we choose 1
        action=choice(available_actions)
#        print("action",action)

        next_state=action
        available_next_actions=[col for col in range(6) if not isnan(R[next_state,col])]
        Q[state,action]=R[state,action] + γ * max([Q[next_state,a] for a in available_next_actions])

        state=next_state

        if state==goal_state:
            break
    print(Q.round())
    print()

[[  0.   0.   0.   0. 400.   0.]
 [  0.   0.   0. 320.   0. 500.]
 [  0.   0.   0. 320.   0.   0.]
 [  0. 400. 256.   0. 400.   0.]
 [320.   0.   0. 320.   0. 500.]
 [  0. 400.   0.   0. 400. 500.]]

[[  0.   0.   0.   0. 400.   0.]
 [  0.   0.   0. 320.   0. 500.]
 [  0.   0.   0. 320.   0.   0.]
 [  0. 400. 256.   0. 400.   0.]
 [320.   0.   0. 320.   0. 500.]
 [  0. 400.   0.   0. 400. 500.]]

[[  0.   0.   0.   0. 400.   0.]
 [  0.   0.   0. 320.   0. 500.]
 [  0.   0.   0. 320.   0.   0.]
 [  0. 400. 256.   0. 400.   0.]
 [320.   0.   0. 320.   0. 500.]
 [  0. 400.   0.   0. 400. 500.]]

[[  0.   0.   0.   0. 400.   0.]
 [  0.   0.   0. 320.   0. 500.]
 [  0.   0.   0. 320.   0.   0.]
 [  0. 400. 256.   0. 400.   0.]
 [320.   0.   0. 320.   0. 500.]
 [  0. 400.   0.   0. 400. 500.]]

[[  0.   0.   0.   0. 400.   0.]
 [  0.   0.   0. 320.   0. 500.]
 [  0.   0.   0. 320.   0.   0.]
 [  0. 400. 256.   0. 400.   0.]
 [320.   0.   0. 320.   0. 500.]
 [  0. 400.   0.   0. 400. 500.]]



In [57]:
Q.round()

array([[  0.,   0.,   0.,   0., 400.,   0.],
       [  0.,   0.,   0., 320.,   0., 500.],
       [  0.,   0.,   0., 320.,   0.,   0.],
       [  0., 400., 256.,   0., 400.,   0.],
       [320.,   0.,   0., 320.,   0., 500.],
       [  0., 400.,   0.,   0., 400., 500.]])